default_context:
  project_name: 'mifarma'
  project_slug: 'mifarma'
  domain_main: 'mifarmacia.app'
  domain_staging: 'stag.mifarmacia.app'
  docker_swarm_stack_name_main: 'mifarmacia-app'
  docker_swarm_stack_name_staging: 'stag-mifarmacia-app'
  secret_key: '1862e2b8307a7379a4666009484d4d633a90b47ef3f224f4bea24ddc43db85f0'
  first_superuser: 'bereyziat.developer@gmail.com'
  first_superuser_password: 'Coucoucmoi67'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.mifarmacia.app", "https://stag.mifarmacia.app", "https://mifarmacia.app", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '465'
  smtp_host: 'smtp.ionos.es'
  smtp_user: 'noreply@mifarmacia.app'
  smtp_password: 'Mifarma_18330*$pswd'
  smtp_emails_from_email: 'noreply@mifarmacia.app'
  postgres_password: '118f8939ca2b073f02ebd35908c1f638339560fe5de314d7ec35a2cbccd6faba'
  pgadmin_default_user: 'bereyziat.developer@gmail.com'
  pgadmin_default_user_password: 'Coucoucmoi67'
  traefik_constraint_tag: 'mifarmacia.app'
  traefik_constraint_tag_staging: 'stag.mifarmacia.app'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:Coucoucmoi67'
  sentry_dsn: ''
  docker_image_prefix: 'bereyziatdev/mifarma/'
  docker_image_backend: 'bereyziatdev/mifarma_backend'
  docker_image_celeryworker: 'bereyziatdev/mifarma_celeryworker'
  docker_image_frontend: 'bereyziatdev/mifarma_frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
