"""Add column refused to table users

Revision ID: 00022379c10a
Revises: d323fb7f7da9
Create Date: 2021-11-16 13:26:43.072092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00022379c10a'
down_revision = 'd323fb7f7da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refused', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET refused = False")
    op.alter_column('users', 'refused', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refused')
    # ### end Alembic commands ###
