"""Add image relationships

Revision ID: 1a8126d9238a
Revises: 00022379c10a
Create Date: 2021-12-06 09:38:54.761357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a8126d9238a'
down_revision = '00022379c10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('images', sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('images', sa.Column('pharmacy_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'images', 'pharmacies', ['pharmacy_id'], ['id'])
    op.create_foreign_key(None, 'images', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'images', 'users', ['user_id'], ['id'])
    op.drop_column('images', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'pharmacy_id')
    op.drop_column('images', 'product_id')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###
