"""Specify ean_code as unique

Revision ID: 2cbf1b81bde7
Revises: 6f52666d4897
Create Date: 2021-08-24 06:21:27.489653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cbf1b81bde7'
down_revision = '6f52666d4897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_ean_code', table_name='products')
    op.create_index(op.f('ix_products_ean_code'), 'products', ['ean_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_ean_code'), table_name='products')
    op.create_index('ix_products_ean_code', 'products', ['ean_code'], unique=False)
    # ### end Alembic commands ###
