"""Add column public ID to table user

Revision ID: 2d4e92995819
Revises: 711c01d3067d
Create Date: 2021-07-30 17:43:57.934438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d4e92995819'
down_revision = '711c01d3067d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.execute("update users set public_id = email")
    op.alter_column('users', 'public_id', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###
