"""Add voucher related columns

Revision ID: 6f52666d4897
Revises: 31e10212a7a2
Create Date: 2021-08-21 11:45:01.015224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f52666d4897'
down_revision = '31e10212a7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('count_for_voucher', sa.Boolean(), nullable=True))
    op.execute("UPDATE orders SET count_for_voucher = True")
    op.alter_column('orders', 'count_for_voucher', nullable=False)
    op.alter_column('orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_index('ix_order_content_id', table_name='orders')
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.add_column('pharmacies', sa.Column('percentage_for_voucher', sa.Integer(), nullable=True))
    op.execute("UPDATE pharmacies SET percentage_for_voucher=0")
    op.alter_column('pharmacies', 'percentage_for_voucher', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pharmacies', 'percentage_for_voucher')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.create_index('ix_order_content_id', 'orders', ['id'], unique=False)
    op.alter_column('orders', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('orders', 'count_for_voucher')
    # ### end Alembic commands ###
