"""Add columns to user

Revision ID: 8f94e9fa6106
Revises: e86fe9ef527f
Create Date: 2021-03-15 04:02:59.758227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f94e9fa6106'
down_revision = 'e86fe9ef527f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('addict', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('alcoholic', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('allergies', sa.String(), nullable=True))
    op.add_column('user', sa.Column('birthdate', sa.Date(), nullable=True))
    # op.add_column('user', sa.Column('gender', sa.Enum('male', 'female', 'non_binary', 'not_specified', name='gender'), nullable=True))
    op.add_column('user', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('user', sa.Column('pregnant', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('smoker', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('weight', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'weight')
    op.drop_column('user', 'smoker')
    op.drop_column('user', 'pregnant')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'height')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'birthdate')
    op.drop_column('user', 'allergies')
    op.drop_column('user', 'alcoholic')
    op.drop_column('user', 'addict')
    # ### end Alembic commands ###
