"""Complete user profile and add roles

Revision ID: 91a9e5a9e53a
Revises: 8f94e9fa6106
Create Date: 2021-03-27 07:40:26.190415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91a9e5a9e53a'
down_revision = '8f94e9fa6106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('postcode', sa.String(), nullable=True))
    op.add_column('user', sa.Column('prescriptions', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('previous_diseases', sa.JSON(), nullable=True))
    op.drop_column('user','allergies')
    op.add_column('user', sa.Column('allergies', sa.JSON(), nullable=True))
    op.alter_column('user', 'height',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'height',
               existing_type=sa.Integer(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('user', 'allergies',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'previous_diseases')
    op.drop_column('user', 'prescriptions')
    op.drop_column('user', 'postcode')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
