"""Add relationships

Revision ID: 9d200bea18ff
Revises: fd432fff18f2
Create Date: 2021-03-31 22:30:52.150464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d200bea18ff'
down_revision = 'fd432fff18f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('address2', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pharmacies_id'), 'pharmacies', ['id'], unique=False)
    op.create_index(op.f('ix_pharmacies_name'), 'pharmacies', ['name'], unique=False)
    op.drop_index('ix_pharmacy_id', table_name='pharmacy')
    op.drop_index('ix_pharmacy_name', table_name='pharmacy')
    op.drop_table('pharmacy')
    op.add_column('drugs', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('discount', sa.Integer(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('users', sa.Column('pharmacy_id', sa.Integer(), nullable=True))
    op.drop_index('ix_user_email', table_name='users')
    op.drop_index('ix_user_id', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_foreign_key(None, 'users', 'pharmacies', ['pharmacy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_user_id', 'users', ['id'], unique=False)
    op.create_index('ix_user_email', 'users', ['email'], unique=True)
    op.alter_column('users', 'previous_diseases',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('users', 'prescriptions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('users', 'allergies',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('users', 'pharmacy_id')
    op.alter_column('products', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('products', 'discount')
    op.drop_column('drugs', 'price')
    op.create_table('pharmacy',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pharmacy_pkey')
    )
    op.create_index('ix_pharmacy_name', 'pharmacy', ['name'], unique=False)
    op.create_index('ix_pharmacy_id', 'pharmacy', ['id'], unique=False)
    op.drop_index(op.f('ix_pharmacies_name'), table_name='pharmacies')
    op.drop_index(op.f('ix_pharmacies_id'), table_name='pharmacies')
    op.drop_table('pharmacies')
    # ### end Alembic commands ###
